(ns frq.moq.raw
  "Every entry point in libmoq_ffi, declared. GENERATED — do not edit.

      just gen-moq

  These are not transcribed from a header. UniFFI embeds its interface
  metadata in the object itself, and `uniffi-bindgen --library` reads it back
  out, so what is declared here is what the .so we load actually exports.

  That distinction is not academic. moq-ffi has `audio` and `video` features,
  on by default, that carry Opus and H.264 — and every Linux and Android
  artifact its release publishes is built WITHOUT them. The C header shipped
  beside those artifacts describes the Apple build, which has them. Three
  different surfaces, one version number:

      the published Linux/Android .so   206 functions, no codecs
      the published C header (Apple)    230 functions
      what the flake builds             230 functions, codecs in

  Binding the header would have linked on a Mac and failed on both platforms
  frq ships to; binding the published Linux object would have compiled and
  then had nowhere to encode a frame. Generating from the object the flake
  builds is what keeps those three from drifting apart silently.

  Nothing here is hand-written and nothing is inferred. The generator maps a
  ctype it does not recognise to nothing at all and reports it, rather than
  guessing a width — a wrong one would be a silent memory bug rather than a
  compile error.

  Two shapes recur, and both are spelled out in full at every call site rather
  than named: `defcfn` is a macro whose types Chez fixes when it COMPILES the
  foreign procedure, so a `def`'d descriptor in type position has nothing to
  compile. Hence the literal [:by-value [:struct ...]] repeated throughout —
  it is the RustBuffer {capacity, len, data} triple, or the ForeignBytes pair.

  A trailing :pointer on a non-async function is its `RustCallStatus *`
  out-parameter; `frq.moq.uniffi/with-out-status` is what supplies one. An
  async function has no status and answers a future handle instead — poll it
  through `frq.moq.uniffi/start-future`.

  Generated from moq-ffi 0.3.17 built with default features, UniFFI contract 30."
  (:require [jolt.ffi :as ffi]))

;; MoqError, as UniFFI numbers it in THIS object. Generated with the
;; entry points above, and for the same reason: the variants are
;; inserted into rather than appended to, so a table written by hand
;; against one build names the wrong error in the next.
(def moq-error-variants
  {1 :protocol
   2 :media
   3 :mux
   4 :json-track
   5 :audio
   6 :video
   7 :url
   8 :time-overflow
   9 :log-level
   10 :task
   11 :json
   12 :cancelled
   13 :closed
   14 :connect
   15 :bind
   16 :reject
   17 :already-responded
   18 :codec
   19 :unauthorized
   20 :forbidden
   21 :not-found
   22 :unsupported
   23 :invalid-route
   24 :log})

(ffi/defcfn rust-future-cancel-f32 "ffi_moq_ffi_rust_future_cancel_f32" [:uint64] :void)
(ffi/defcfn rust-future-cancel-f64 "ffi_moq_ffi_rust_future_cancel_f64" [:uint64] :void)
(ffi/defcfn rust-future-cancel-i16 "ffi_moq_ffi_rust_future_cancel_i16" [:uint64] :void)
(ffi/defcfn rust-future-cancel-i32 "ffi_moq_ffi_rust_future_cancel_i32" [:uint64] :void)
(ffi/defcfn rust-future-cancel-i64 "ffi_moq_ffi_rust_future_cancel_i64" [:uint64] :void)
(ffi/defcfn rust-future-cancel-i8 "ffi_moq_ffi_rust_future_cancel_i8" [:uint64] :void)
(ffi/defcfn rust-future-cancel-rust-buffer "ffi_moq_ffi_rust_future_cancel_rust_buffer" [:uint64] :void)
(ffi/defcfn rust-future-cancel-u16 "ffi_moq_ffi_rust_future_cancel_u16" [:uint64] :void)
(ffi/defcfn rust-future-cancel-u32 "ffi_moq_ffi_rust_future_cancel_u32" [:uint64] :void)
(ffi/defcfn rust-future-cancel-u64 "ffi_moq_ffi_rust_future_cancel_u64" [:uint64] :void)
(ffi/defcfn rust-future-cancel-u8 "ffi_moq_ffi_rust_future_cancel_u8" [:uint64] :void)
(ffi/defcfn rust-future-cancel-void "ffi_moq_ffi_rust_future_cancel_void" [:uint64] :void)
(ffi/defcfn rust-future-complete-f32 "ffi_moq_ffi_rust_future_complete_f32" [:uint64 :pointer] :float)
(ffi/defcfn rust-future-complete-f64 "ffi_moq_ffi_rust_future_complete_f64" [:uint64 :pointer] :double)
(ffi/defcfn rust-future-complete-i16 "ffi_moq_ffi_rust_future_complete_i16" [:uint64 :pointer] :int16)
(ffi/defcfn rust-future-complete-i32 "ffi_moq_ffi_rust_future_complete_i32" [:uint64 :pointer] :int32)
(ffi/defcfn rust-future-complete-i64 "ffi_moq_ffi_rust_future_complete_i64" [:uint64 :pointer] :int64)
(ffi/defcfn rust-future-complete-i8 "ffi_moq_ffi_rust_future_complete_i8" [:uint64 :pointer] :int8)
(ffi/defcfn rust-future-complete-rust-buffer "ffi_moq_ffi_rust_future_complete_rust_buffer" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn rust-future-complete-u16 "ffi_moq_ffi_rust_future_complete_u16" [:uint64 :pointer] :uint16)
(ffi/defcfn rust-future-complete-u32 "ffi_moq_ffi_rust_future_complete_u32" [:uint64 :pointer] :uint32)
(ffi/defcfn rust-future-complete-u64 "ffi_moq_ffi_rust_future_complete_u64" [:uint64 :pointer] :uint64)
(ffi/defcfn rust-future-complete-u8 "ffi_moq_ffi_rust_future_complete_u8" [:uint64 :pointer] :uint8)
(ffi/defcfn rust-future-complete-void "ffi_moq_ffi_rust_future_complete_void" [:uint64 :pointer] :void)
(ffi/defcfn rust-future-free-f32 "ffi_moq_ffi_rust_future_free_f32" [:uint64] :void)
(ffi/defcfn rust-future-free-f64 "ffi_moq_ffi_rust_future_free_f64" [:uint64] :void)
(ffi/defcfn rust-future-free-i16 "ffi_moq_ffi_rust_future_free_i16" [:uint64] :void)
(ffi/defcfn rust-future-free-i32 "ffi_moq_ffi_rust_future_free_i32" [:uint64] :void)
(ffi/defcfn rust-future-free-i64 "ffi_moq_ffi_rust_future_free_i64" [:uint64] :void)
(ffi/defcfn rust-future-free-i8 "ffi_moq_ffi_rust_future_free_i8" [:uint64] :void)
(ffi/defcfn rust-future-free-rust-buffer "ffi_moq_ffi_rust_future_free_rust_buffer" [:uint64] :void)
(ffi/defcfn rust-future-free-u16 "ffi_moq_ffi_rust_future_free_u16" [:uint64] :void)
(ffi/defcfn rust-future-free-u32 "ffi_moq_ffi_rust_future_free_u32" [:uint64] :void)
(ffi/defcfn rust-future-free-u64 "ffi_moq_ffi_rust_future_free_u64" [:uint64] :void)
(ffi/defcfn rust-future-free-u8 "ffi_moq_ffi_rust_future_free_u8" [:uint64] :void)
(ffi/defcfn rust-future-free-void "ffi_moq_ffi_rust_future_free_void" [:uint64] :void)
(ffi/defcfn rust-future-poll-f32 "ffi_moq_ffi_rust_future_poll_f32" [:uint64 :pointer :uint64] :void)
(ffi/defcfn rust-future-poll-f64 "ffi_moq_ffi_rust_future_poll_f64" [:uint64 :pointer :uint64] :void)
(ffi/defcfn rust-future-poll-i16 "ffi_moq_ffi_rust_future_poll_i16" [:uint64 :pointer :uint64] :void)
(ffi/defcfn rust-future-poll-i32 "ffi_moq_ffi_rust_future_poll_i32" [:uint64 :pointer :uint64] :void)
(ffi/defcfn rust-future-poll-i64 "ffi_moq_ffi_rust_future_poll_i64" [:uint64 :pointer :uint64] :void)
(ffi/defcfn rust-future-poll-i8 "ffi_moq_ffi_rust_future_poll_i8" [:uint64 :pointer :uint64] :void)
(ffi/defcfn rust-future-poll-rust-buffer "ffi_moq_ffi_rust_future_poll_rust_buffer" [:uint64 :pointer :uint64] :void)
(ffi/defcfn rust-future-poll-u16 "ffi_moq_ffi_rust_future_poll_u16" [:uint64 :pointer :uint64] :void)
(ffi/defcfn rust-future-poll-u32 "ffi_moq_ffi_rust_future_poll_u32" [:uint64 :pointer :uint64] :void)
(ffi/defcfn rust-future-poll-u64 "ffi_moq_ffi_rust_future_poll_u64" [:uint64 :pointer :uint64] :void)
(ffi/defcfn rust-future-poll-u8 "ffi_moq_ffi_rust_future_poll_u8" [:uint64 :pointer :uint64] :void)
(ffi/defcfn rust-future-poll-void "ffi_moq_ffi_rust_future_poll_void" [:uint64 :pointer :uint64] :void)
(ffi/defcfn rustbuffer-alloc "ffi_moq_ffi_rustbuffer_alloc" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn rustbuffer-free "ffi_moq_ffi_rustbuffer_free" [[:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn rustbuffer-from-bytes "ffi_moq_ffi_rustbuffer_from_bytes" [[:by-value [:struct [[:len :int32] [:data :pointer]]]] :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn rustbuffer-reserve "ffi_moq_ffi_rustbuffer_reserve" [[:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn uniffi-contract-version "ffi_moq_ffi_uniffi_contract_version" [] :uint32)
(ffi/defcfn checksum-constructor-moqbroadcastproducer-new "uniffi_moq_ffi_checksum_constructor_moqbroadcastproducer_new" [] :uint16)
(ffi/defcfn checksum-constructor-moqclient-new "uniffi_moq_ffi_checksum_constructor_moqclient_new" [] :uint16)
(ffi/defcfn checksum-constructor-moqoriginproducer-new "uniffi_moq_ffi_checksum_constructor_moqoriginproducer_new" [] :uint16)
(ffi/defcfn checksum-constructor-moqserver-new "uniffi_moq_ffi_checksum_constructor_moqserver_new" [] :uint16)
(ffi/defcfn checksum-func-moq-log-level "uniffi_moq_ffi_checksum_func_moq_log_level" [] :uint16)
(ffi/defcfn checksum-method-moqannounced-cancel "uniffi_moq_ffi_checksum_method_moqannounced_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqannounced-next "uniffi_moq_ffi_checksum_method_moqannounced_next" [] :uint16)
(ffi/defcfn checksum-method-moqannouncedbroadcast-available "uniffi_moq_ffi_checksum_method_moqannouncedbroadcast_available" [] :uint16)
(ffi/defcfn checksum-method-moqannouncedbroadcast-cancel "uniffi_moq_ffi_checksum_method_moqannouncedbroadcast_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqannouncement-broadcast "uniffi_moq_ffi_checksum_method_moqannouncement_broadcast" [] :uint16)
(ffi/defcfn checksum-method-moqannouncement-path "uniffi_moq_ffi_checksum_method_moqannouncement_path" [] :uint16)
(ffi/defcfn checksum-method-moqaudioconsumer-cancel "uniffi_moq_ffi_checksum_method_moqaudioconsumer_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqaudioconsumer-next "uniffi_moq_ffi_checksum_method_moqaudioconsumer_next" [] :uint16)
(ffi/defcfn checksum-method-moqaudioproducer-finish "uniffi_moq_ffi_checksum_method_moqaudioproducer_finish" [] :uint16)
(ffi/defcfn checksum-method-moqaudioproducer-name "uniffi_moq_ffi_checksum_method_moqaudioproducer_name" [] :uint16)
(ffi/defcfn checksum-method-moqaudioproducer-reset-epoch "uniffi_moq_ffi_checksum_method_moqaudioproducer_reset_epoch" [] :uint16)
(ffi/defcfn checksum-method-moqaudioproducer-unused "uniffi_moq_ffi_checksum_method_moqaudioproducer_unused" [] :uint16)
(ffi/defcfn checksum-method-moqaudioproducer-used "uniffi_moq_ffi_checksum_method_moqaudioproducer_used" [] :uint16)
(ffi/defcfn checksum-method-moqaudioproducer-write "uniffi_moq_ffi_checksum_method_moqaudioproducer_write" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastconsumer-fetch-group "uniffi_moq_ffi_checksum_method_moqbroadcastconsumer_fetch_group" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastconsumer-fetch-media-group "uniffi_moq_ffi_checksum_method_moqbroadcastconsumer_fetch_media_group" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastconsumer-route "uniffi_moq_ffi_checksum_method_moqbroadcastconsumer_route" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastconsumer-route-updates "uniffi_moq_ffi_checksum_method_moqbroadcastconsumer_route_updates" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastconsumer-subscribe-audio "uniffi_moq_ffi_checksum_method_moqbroadcastconsumer_subscribe_audio" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastconsumer-subscribe-catalog "uniffi_moq_ffi_checksum_method_moqbroadcastconsumer_subscribe_catalog" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastconsumer-subscribe-json-snapshot "uniffi_moq_ffi_checksum_method_moqbroadcastconsumer_subscribe_json_snapshot" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastconsumer-subscribe-json-stream "uniffi_moq_ffi_checksum_method_moqbroadcastconsumer_subscribe_json_stream" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastconsumer-subscribe-media "uniffi_moq_ffi_checksum_method_moqbroadcastconsumer_subscribe_media" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastconsumer-subscribe-track "uniffi_moq_ffi_checksum_method_moqbroadcastconsumer_subscribe_track" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastdynamic-cancel "uniffi_moq_ffi_checksum_method_moqbroadcastdynamic_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastdynamic-requested-track "uniffi_moq_ffi_checksum_method_moqbroadcastdynamic_requested_track" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-consume "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_consume" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-dynamic "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_dynamic" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-finish "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_finish" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-publish-audio "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_publish_audio" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-publish-json-snapshot "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_publish_json_snapshot" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-publish-json-stream "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_publish_json_stream" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-publish-media "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_publish_media" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-publish-media-on-track "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_publish_media_on_track" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-publish-media-stream "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_publish_media_stream" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-publish-track "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_publish_track" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-publish-video "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_publish_video" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-remove-catalog-section "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_remove_catalog_section" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-set-announce "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_set_announce" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-set-catalog-section "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_set_catalog_section" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-set-route "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_set_route" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastproducer-set-video-properties "uniffi_moq_ffi_checksum_method_moqbroadcastproducer_set_video_properties" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastrequest-abort "uniffi_moq_ffi_checksum_method_moqbroadcastrequest_abort" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastrequest-accept "uniffi_moq_ffi_checksum_method_moqbroadcastrequest_accept" [] :uint16)
(ffi/defcfn checksum-method-moqbroadcastrequest-path "uniffi_moq_ffi_checksum_method_moqbroadcastrequest_path" [] :uint16)
(ffi/defcfn checksum-method-moqcatalogconsumer-cancel "uniffi_moq_ffi_checksum_method_moqcatalogconsumer_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqcatalogconsumer-next "uniffi_moq_ffi_checksum_method_moqcatalogconsumer_next" [] :uint16)
(ffi/defcfn checksum-method-moqclient-cancel "uniffi_moq_ffi_checksum_method_moqclient_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqclient-connect "uniffi_moq_ffi_checksum_method_moqclient_connect" [] :uint16)
(ffi/defcfn checksum-method-moqclient-set-bind "uniffi_moq_ffi_checksum_method_moqclient_set_bind" [] :uint16)
(ffi/defcfn checksum-method-moqclient-set-consume "uniffi_moq_ffi_checksum_method_moqclient_set_consume" [] :uint16)
(ffi/defcfn checksum-method-moqclient-set-publish "uniffi_moq_ffi_checksum_method_moqclient_set_publish" [] :uint16)
(ffi/defcfn checksum-method-moqclient-set-tls-cert "uniffi_moq_ffi_checksum_method_moqclient_set_tls_cert" [] :uint16)
(ffi/defcfn checksum-method-moqclient-set-tls-disable-verify "uniffi_moq_ffi_checksum_method_moqclient_set_tls_disable_verify" [] :uint16)
(ffi/defcfn checksum-method-moqclient-set-tls-fingerprints "uniffi_moq_ffi_checksum_method_moqclient_set_tls_fingerprints" [] :uint16)
(ffi/defcfn checksum-method-moqclient-set-tls-key "uniffi_moq_ffi_checksum_method_moqclient_set_tls_key" [] :uint16)
(ffi/defcfn checksum-method-moqclient-set-tls-roots "uniffi_moq_ffi_checksum_method_moqclient_set_tls_roots" [] :uint16)
(ffi/defcfn checksum-method-moqclient-set-tls-system-roots "uniffi_moq_ffi_checksum_method_moqclient_set_tls_system_roots" [] :uint16)
(ffi/defcfn checksum-method-moqgroupconsumer-cancel "uniffi_moq_ffi_checksum_method_moqgroupconsumer_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqgroupconsumer-read-frame "uniffi_moq_ffi_checksum_method_moqgroupconsumer_read_frame" [] :uint16)
(ffi/defcfn checksum-method-moqgroupconsumer-sequence "uniffi_moq_ffi_checksum_method_moqgroupconsumer_sequence" [] :uint16)
(ffi/defcfn checksum-method-moqgroupproducer-abort "uniffi_moq_ffi_checksum_method_moqgroupproducer_abort" [] :uint16)
(ffi/defcfn checksum-method-moqgroupproducer-consume "uniffi_moq_ffi_checksum_method_moqgroupproducer_consume" [] :uint16)
(ffi/defcfn checksum-method-moqgroupproducer-finish "uniffi_moq_ffi_checksum_method_moqgroupproducer_finish" [] :uint16)
(ffi/defcfn checksum-method-moqgroupproducer-sequence "uniffi_moq_ffi_checksum_method_moqgroupproducer_sequence" [] :uint16)
(ffi/defcfn checksum-method-moqgroupproducer-write-frame "uniffi_moq_ffi_checksum_method_moqgroupproducer_write_frame" [] :uint16)
(ffi/defcfn checksum-method-moqgrouprequest-abort "uniffi_moq_ffi_checksum_method_moqgrouprequest_abort" [] :uint16)
(ffi/defcfn checksum-method-moqgrouprequest-accept "uniffi_moq_ffi_checksum_method_moqgrouprequest_accept" [] :uint16)
(ffi/defcfn checksum-method-moqgrouprequest-priority "uniffi_moq_ffi_checksum_method_moqgrouprequest_priority" [] :uint16)
(ffi/defcfn checksum-method-moqgrouprequest-sequence "uniffi_moq_ffi_checksum_method_moqgrouprequest_sequence" [] :uint16)
(ffi/defcfn checksum-method-moqjsonsnapshotconsumer-cancel "uniffi_moq_ffi_checksum_method_moqjsonsnapshotconsumer_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqjsonsnapshotconsumer-next "uniffi_moq_ffi_checksum_method_moqjsonsnapshotconsumer_next" [] :uint16)
(ffi/defcfn checksum-method-moqjsonsnapshotproducer-finish "uniffi_moq_ffi_checksum_method_moqjsonsnapshotproducer_finish" [] :uint16)
(ffi/defcfn checksum-method-moqjsonsnapshotproducer-update "uniffi_moq_ffi_checksum_method_moqjsonsnapshotproducer_update" [] :uint16)
(ffi/defcfn checksum-method-moqjsonstreamconsumer-cancel "uniffi_moq_ffi_checksum_method_moqjsonstreamconsumer_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqjsonstreamconsumer-next "uniffi_moq_ffi_checksum_method_moqjsonstreamconsumer_next" [] :uint16)
(ffi/defcfn checksum-method-moqjsonstreamproducer-append "uniffi_moq_ffi_checksum_method_moqjsonstreamproducer_append" [] :uint16)
(ffi/defcfn checksum-method-moqjsonstreamproducer-finish "uniffi_moq_ffi_checksum_method_moqjsonstreamproducer_finish" [] :uint16)
(ffi/defcfn checksum-method-moqmediaconsumer-cancel "uniffi_moq_ffi_checksum_method_moqmediaconsumer_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqmediaconsumer-next "uniffi_moq_ffi_checksum_method_moqmediaconsumer_next" [] :uint16)
(ffi/defcfn checksum-method-moqmediagroupconsumer-cancel "uniffi_moq_ffi_checksum_method_moqmediagroupconsumer_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqmediagroupconsumer-next "uniffi_moq_ffi_checksum_method_moqmediagroupconsumer_next" [] :uint16)
(ffi/defcfn checksum-method-moqmediagroupconsumer-sequence "uniffi_moq_ffi_checksum_method_moqmediagroupconsumer_sequence" [] :uint16)
(ffi/defcfn checksum-method-moqmediaproducer-finish "uniffi_moq_ffi_checksum_method_moqmediaproducer_finish" [] :uint16)
(ffi/defcfn checksum-method-moqmediaproducer-name "uniffi_moq_ffi_checksum_method_moqmediaproducer_name" [] :uint16)
(ffi/defcfn checksum-method-moqmediaproducer-unused "uniffi_moq_ffi_checksum_method_moqmediaproducer_unused" [] :uint16)
(ffi/defcfn checksum-method-moqmediaproducer-used "uniffi_moq_ffi_checksum_method_moqmediaproducer_used" [] :uint16)
(ffi/defcfn checksum-method-moqmediaproducer-write-frame "uniffi_moq_ffi_checksum_method_moqmediaproducer_write_frame" [] :uint16)
(ffi/defcfn checksum-method-moqmediastreamproducer-finish "uniffi_moq_ffi_checksum_method_moqmediastreamproducer_finish" [] :uint16)
(ffi/defcfn checksum-method-moqmediastreamproducer-write "uniffi_moq_ffi_checksum_method_moqmediastreamproducer_write" [] :uint16)
(ffi/defcfn checksum-method-moqoriginconsumer-announced "uniffi_moq_ffi_checksum_method_moqoriginconsumer_announced" [] :uint16)
(ffi/defcfn checksum-method-moqoriginconsumer-announced-broadcast "uniffi_moq_ffi_checksum_method_moqoriginconsumer_announced_broadcast" [] :uint16)
(ffi/defcfn checksum-method-moqoriginconsumer-request-broadcast "uniffi_moq_ffi_checksum_method_moqoriginconsumer_request_broadcast" [] :uint16)
(ffi/defcfn checksum-method-moqorigindynamic-cancel "uniffi_moq_ffi_checksum_method_moqorigindynamic_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqorigindynamic-requested-broadcast "uniffi_moq_ffi_checksum_method_moqorigindynamic_requested_broadcast" [] :uint16)
(ffi/defcfn checksum-method-moqoriginproducer-consume "uniffi_moq_ffi_checksum_method_moqoriginproducer_consume" [] :uint16)
(ffi/defcfn checksum-method-moqoriginproducer-create-broadcast "uniffi_moq_ffi_checksum_method_moqoriginproducer_create_broadcast" [] :uint16)
(ffi/defcfn checksum-method-moqoriginproducer-dynamic "uniffi_moq_ffi_checksum_method_moqoriginproducer_dynamic" [] :uint16)
(ffi/defcfn checksum-method-moqrequest-accept "uniffi_moq_ffi_checksum_method_moqrequest_accept" [] :uint16)
(ffi/defcfn checksum-method-moqrequest-cancel "uniffi_moq_ffi_checksum_method_moqrequest_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqrequest-path "uniffi_moq_ffi_checksum_method_moqrequest_path" [] :uint16)
(ffi/defcfn checksum-method-moqrequest-query "uniffi_moq_ffi_checksum_method_moqrequest_query" [] :uint16)
(ffi/defcfn checksum-method-moqrequest-reject "uniffi_moq_ffi_checksum_method_moqrequest_reject" [] :uint16)
(ffi/defcfn checksum-method-moqrequest-set-consume "uniffi_moq_ffi_checksum_method_moqrequest_set_consume" [] :uint16)
(ffi/defcfn checksum-method-moqrequest-set-publish "uniffi_moq_ffi_checksum_method_moqrequest_set_publish" [] :uint16)
(ffi/defcfn checksum-method-moqrequest-transport "uniffi_moq_ffi_checksum_method_moqrequest_transport" [] :uint16)
(ffi/defcfn checksum-method-moqrequest-url "uniffi_moq_ffi_checksum_method_moqrequest_url" [] :uint16)
(ffi/defcfn checksum-method-moqroutewatch-cancel "uniffi_moq_ffi_checksum_method_moqroutewatch_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqroutewatch-next "uniffi_moq_ffi_checksum_method_moqroutewatch_next" [] :uint16)
(ffi/defcfn checksum-method-moqserver-accept "uniffi_moq_ffi_checksum_method_moqserver_accept" [] :uint16)
(ffi/defcfn checksum-method-moqserver-cancel "uniffi_moq_ffi_checksum_method_moqserver_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqserver-cert-fingerprints "uniffi_moq_ffi_checksum_method_moqserver_cert_fingerprints" [] :uint16)
(ffi/defcfn checksum-method-moqserver-listen "uniffi_moq_ffi_checksum_method_moqserver_listen" [] :uint16)
(ffi/defcfn checksum-method-moqserver-set-bind "uniffi_moq_ffi_checksum_method_moqserver_set_bind" [] :uint16)
(ffi/defcfn checksum-method-moqserver-set-consume "uniffi_moq_ffi_checksum_method_moqserver_set_consume" [] :uint16)
(ffi/defcfn checksum-method-moqserver-set-publish "uniffi_moq_ffi_checksum_method_moqserver_set_publish" [] :uint16)
(ffi/defcfn checksum-method-moqserver-set-tls-cert "uniffi_moq_ffi_checksum_method_moqserver_set_tls_cert" [] :uint16)
(ffi/defcfn checksum-method-moqserver-set-tls-generate "uniffi_moq_ffi_checksum_method_moqserver_set_tls_generate" [] :uint16)
(ffi/defcfn checksum-method-moqserver-set-tls-key "uniffi_moq_ffi_checksum_method_moqserver_set_tls_key" [] :uint16)
(ffi/defcfn checksum-method-moqsession-cancel "uniffi_moq_ffi_checksum_method_moqsession_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqsession-closed "uniffi_moq_ffi_checksum_method_moqsession_closed" [] :uint16)
(ffi/defcfn checksum-method-moqsession-consumer "uniffi_moq_ffi_checksum_method_moqsession_consumer" [] :uint16)
(ffi/defcfn checksum-method-moqsession-publisher "uniffi_moq_ffi_checksum_method_moqsession_publisher" [] :uint16)
(ffi/defcfn checksum-method-moqsession-shutdown "uniffi_moq_ffi_checksum_method_moqsession_shutdown" [] :uint16)
(ffi/defcfn checksum-method-moqsession-stats "uniffi_moq_ffi_checksum_method_moqsession_stats" [] :uint16)
(ffi/defcfn checksum-method-moqtrackconsumer-cancel "uniffi_moq_ffi_checksum_method_moqtrackconsumer_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqtrackconsumer-info "uniffi_moq_ffi_checksum_method_moqtrackconsumer_info" [] :uint16)
(ffi/defcfn checksum-method-moqtrackconsumer-next-group "uniffi_moq_ffi_checksum_method_moqtrackconsumer_next_group" [] :uint16)
(ffi/defcfn checksum-method-moqtrackconsumer-read-frame "uniffi_moq_ffi_checksum_method_moqtrackconsumer_read_frame" [] :uint16)
(ffi/defcfn checksum-method-moqtrackconsumer-recv-datagram "uniffi_moq_ffi_checksum_method_moqtrackconsumer_recv_datagram" [] :uint16)
(ffi/defcfn checksum-method-moqtrackconsumer-recv-group "uniffi_moq_ffi_checksum_method_moqtrackconsumer_recv_group" [] :uint16)
(ffi/defcfn checksum-method-moqtrackconsumer-update "uniffi_moq_ffi_checksum_method_moqtrackconsumer_update" [] :uint16)
(ffi/defcfn checksum-method-moqtrackdynamic-cancel "uniffi_moq_ffi_checksum_method_moqtrackdynamic_cancel" [] :uint16)
(ffi/defcfn checksum-method-moqtrackdynamic-requested-group "uniffi_moq_ffi_checksum_method_moqtrackdynamic_requested_group" [] :uint16)
(ffi/defcfn checksum-method-moqtrackproducer-abort "uniffi_moq_ffi_checksum_method_moqtrackproducer_abort" [] :uint16)
(ffi/defcfn checksum-method-moqtrackproducer-append-datagram "uniffi_moq_ffi_checksum_method_moqtrackproducer_append_datagram" [] :uint16)
(ffi/defcfn checksum-method-moqtrackproducer-append-group "uniffi_moq_ffi_checksum_method_moqtrackproducer_append_group" [] :uint16)
(ffi/defcfn checksum-method-moqtrackproducer-consume "uniffi_moq_ffi_checksum_method_moqtrackproducer_consume" [] :uint16)
(ffi/defcfn checksum-method-moqtrackproducer-create-group "uniffi_moq_ffi_checksum_method_moqtrackproducer_create_group" [] :uint16)
(ffi/defcfn checksum-method-moqtrackproducer-dynamic "uniffi_moq_ffi_checksum_method_moqtrackproducer_dynamic" [] :uint16)
(ffi/defcfn checksum-method-moqtrackproducer-finish "uniffi_moq_ffi_checksum_method_moqtrackproducer_finish" [] :uint16)
(ffi/defcfn checksum-method-moqtrackproducer-finish-at "uniffi_moq_ffi_checksum_method_moqtrackproducer_finish_at" [] :uint16)
(ffi/defcfn checksum-method-moqtrackproducer-name "uniffi_moq_ffi_checksum_method_moqtrackproducer_name" [] :uint16)
(ffi/defcfn checksum-method-moqtrackproducer-unused "uniffi_moq_ffi_checksum_method_moqtrackproducer_unused" [] :uint16)
(ffi/defcfn checksum-method-moqtrackproducer-used "uniffi_moq_ffi_checksum_method_moqtrackproducer_used" [] :uint16)
(ffi/defcfn checksum-method-moqtrackproducer-write-frame "uniffi_moq_ffi_checksum_method_moqtrackproducer_write_frame" [] :uint16)
(ffi/defcfn checksum-method-moqtrackrequest-abort "uniffi_moq_ffi_checksum_method_moqtrackrequest_abort" [] :uint16)
(ffi/defcfn checksum-method-moqtrackrequest-accept "uniffi_moq_ffi_checksum_method_moqtrackrequest_accept" [] :uint16)
(ffi/defcfn checksum-method-moqtrackrequest-dynamic "uniffi_moq_ffi_checksum_method_moqtrackrequest_dynamic" [] :uint16)
(ffi/defcfn checksum-method-moqtrackrequest-name "uniffi_moq_ffi_checksum_method_moqtrackrequest_name" [] :uint16)
(ffi/defcfn checksum-method-moqvideoproducer-cut "uniffi_moq_ffi_checksum_method_moqvideoproducer_cut" [] :uint16)
(ffi/defcfn checksum-method-moqvideoproducer-finish "uniffi_moq_ffi_checksum_method_moqvideoproducer_finish" [] :uint16)
(ffi/defcfn checksum-method-moqvideoproducer-name "uniffi_moq_ffi_checksum_method_moqvideoproducer_name" [] :uint16)
(ffi/defcfn checksum-method-moqvideoproducer-set-bitrate "uniffi_moq_ffi_checksum_method_moqvideoproducer_set_bitrate" [] :uint16)
(ffi/defcfn checksum-method-moqvideoproducer-unused "uniffi_moq_ffi_checksum_method_moqvideoproducer_unused" [] :uint16)
(ffi/defcfn checksum-method-moqvideoproducer-used "uniffi_moq_ffi_checksum_method_moqvideoproducer_used" [] :uint16)
(ffi/defcfn checksum-method-moqvideoproducer-write "uniffi_moq_ffi_checksum_method_moqvideoproducer_write" [] :uint16)
(ffi/defcfn clone-moqannounced "uniffi_moq_ffi_fn_clone_moqannounced" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqannouncedbroadcast "uniffi_moq_ffi_fn_clone_moqannouncedbroadcast" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqannouncement "uniffi_moq_ffi_fn_clone_moqannouncement" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqaudioconsumer "uniffi_moq_ffi_fn_clone_moqaudioconsumer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqaudioproducer "uniffi_moq_ffi_fn_clone_moqaudioproducer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqbroadcastconsumer "uniffi_moq_ffi_fn_clone_moqbroadcastconsumer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqbroadcastdynamic "uniffi_moq_ffi_fn_clone_moqbroadcastdynamic" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqbroadcastproducer "uniffi_moq_ffi_fn_clone_moqbroadcastproducer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqbroadcastrequest "uniffi_moq_ffi_fn_clone_moqbroadcastrequest" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqcatalogconsumer "uniffi_moq_ffi_fn_clone_moqcatalogconsumer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqclient "uniffi_moq_ffi_fn_clone_moqclient" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqgroupconsumer "uniffi_moq_ffi_fn_clone_moqgroupconsumer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqgroupproducer "uniffi_moq_ffi_fn_clone_moqgroupproducer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqgrouprequest "uniffi_moq_ffi_fn_clone_moqgrouprequest" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqjsonsnapshotconsumer "uniffi_moq_ffi_fn_clone_moqjsonsnapshotconsumer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqjsonsnapshotproducer "uniffi_moq_ffi_fn_clone_moqjsonsnapshotproducer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqjsonstreamconsumer "uniffi_moq_ffi_fn_clone_moqjsonstreamconsumer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqjsonstreamproducer "uniffi_moq_ffi_fn_clone_moqjsonstreamproducer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqmediaconsumer "uniffi_moq_ffi_fn_clone_moqmediaconsumer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqmediagroupconsumer "uniffi_moq_ffi_fn_clone_moqmediagroupconsumer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqmediaproducer "uniffi_moq_ffi_fn_clone_moqmediaproducer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqmediastreamproducer "uniffi_moq_ffi_fn_clone_moqmediastreamproducer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqoriginconsumer "uniffi_moq_ffi_fn_clone_moqoriginconsumer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqorigindynamic "uniffi_moq_ffi_fn_clone_moqorigindynamic" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqoriginproducer "uniffi_moq_ffi_fn_clone_moqoriginproducer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqrequest "uniffi_moq_ffi_fn_clone_moqrequest" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqroutewatch "uniffi_moq_ffi_fn_clone_moqroutewatch" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqserver "uniffi_moq_ffi_fn_clone_moqserver" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqsession "uniffi_moq_ffi_fn_clone_moqsession" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqtrackconsumer "uniffi_moq_ffi_fn_clone_moqtrackconsumer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqtrackdynamic "uniffi_moq_ffi_fn_clone_moqtrackdynamic" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqtrackproducer "uniffi_moq_ffi_fn_clone_moqtrackproducer" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqtrackrequest "uniffi_moq_ffi_fn_clone_moqtrackrequest" [:uint64 :pointer] :uint64)
(ffi/defcfn clone-moqvideoproducer "uniffi_moq_ffi_fn_clone_moqvideoproducer" [:uint64 :pointer] :uint64)
(ffi/defcfn constructor-moqbroadcastproducer-new "uniffi_moq_ffi_fn_constructor_moqbroadcastproducer_new" [:pointer] :uint64)
(ffi/defcfn constructor-moqclient-new "uniffi_moq_ffi_fn_constructor_moqclient_new" [:pointer] :uint64)
(ffi/defcfn constructor-moqoriginproducer-new "uniffi_moq_ffi_fn_constructor_moqoriginproducer_new" [[:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn constructor-moqserver-new "uniffi_moq_ffi_fn_constructor_moqserver_new" [:pointer] :uint64)
(ffi/defcfn free-moqannounced "uniffi_moq_ffi_fn_free_moqannounced" [:uint64 :pointer] :void)
(ffi/defcfn free-moqannouncedbroadcast "uniffi_moq_ffi_fn_free_moqannouncedbroadcast" [:uint64 :pointer] :void)
(ffi/defcfn free-moqannouncement "uniffi_moq_ffi_fn_free_moqannouncement" [:uint64 :pointer] :void)
(ffi/defcfn free-moqaudioconsumer "uniffi_moq_ffi_fn_free_moqaudioconsumer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqaudioproducer "uniffi_moq_ffi_fn_free_moqaudioproducer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqbroadcastconsumer "uniffi_moq_ffi_fn_free_moqbroadcastconsumer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqbroadcastdynamic "uniffi_moq_ffi_fn_free_moqbroadcastdynamic" [:uint64 :pointer] :void)
(ffi/defcfn free-moqbroadcastproducer "uniffi_moq_ffi_fn_free_moqbroadcastproducer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqbroadcastrequest "uniffi_moq_ffi_fn_free_moqbroadcastrequest" [:uint64 :pointer] :void)
(ffi/defcfn free-moqcatalogconsumer "uniffi_moq_ffi_fn_free_moqcatalogconsumer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqclient "uniffi_moq_ffi_fn_free_moqclient" [:uint64 :pointer] :void)
(ffi/defcfn free-moqgroupconsumer "uniffi_moq_ffi_fn_free_moqgroupconsumer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqgroupproducer "uniffi_moq_ffi_fn_free_moqgroupproducer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqgrouprequest "uniffi_moq_ffi_fn_free_moqgrouprequest" [:uint64 :pointer] :void)
(ffi/defcfn free-moqjsonsnapshotconsumer "uniffi_moq_ffi_fn_free_moqjsonsnapshotconsumer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqjsonsnapshotproducer "uniffi_moq_ffi_fn_free_moqjsonsnapshotproducer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqjsonstreamconsumer "uniffi_moq_ffi_fn_free_moqjsonstreamconsumer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqjsonstreamproducer "uniffi_moq_ffi_fn_free_moqjsonstreamproducer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqmediaconsumer "uniffi_moq_ffi_fn_free_moqmediaconsumer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqmediagroupconsumer "uniffi_moq_ffi_fn_free_moqmediagroupconsumer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqmediaproducer "uniffi_moq_ffi_fn_free_moqmediaproducer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqmediastreamproducer "uniffi_moq_ffi_fn_free_moqmediastreamproducer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqoriginconsumer "uniffi_moq_ffi_fn_free_moqoriginconsumer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqorigindynamic "uniffi_moq_ffi_fn_free_moqorigindynamic" [:uint64 :pointer] :void)
(ffi/defcfn free-moqoriginproducer "uniffi_moq_ffi_fn_free_moqoriginproducer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqrequest "uniffi_moq_ffi_fn_free_moqrequest" [:uint64 :pointer] :void)
(ffi/defcfn free-moqroutewatch "uniffi_moq_ffi_fn_free_moqroutewatch" [:uint64 :pointer] :void)
(ffi/defcfn free-moqserver "uniffi_moq_ffi_fn_free_moqserver" [:uint64 :pointer] :void)
(ffi/defcfn free-moqsession "uniffi_moq_ffi_fn_free_moqsession" [:uint64 :pointer] :void)
(ffi/defcfn free-moqtrackconsumer "uniffi_moq_ffi_fn_free_moqtrackconsumer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqtrackdynamic "uniffi_moq_ffi_fn_free_moqtrackdynamic" [:uint64 :pointer] :void)
(ffi/defcfn free-moqtrackproducer "uniffi_moq_ffi_fn_free_moqtrackproducer" [:uint64 :pointer] :void)
(ffi/defcfn free-moqtrackrequest "uniffi_moq_ffi_fn_free_moqtrackrequest" [:uint64 :pointer] :void)
(ffi/defcfn free-moqvideoproducer "uniffi_moq_ffi_fn_free_moqvideoproducer" [:uint64 :pointer] :void)
(ffi/defcfn func-moq-log-level "uniffi_moq_ffi_fn_func_moq_log_level" [[:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqannounced-cancel "uniffi_moq_ffi_fn_method_moqannounced_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqannounced-next "uniffi_moq_ffi_fn_method_moqannounced_next" [:uint64] :uint64)
(ffi/defcfn method-moqannouncedbroadcast-available "uniffi_moq_ffi_fn_method_moqannouncedbroadcast_available" [:uint64] :uint64)
(ffi/defcfn method-moqannouncedbroadcast-cancel "uniffi_moq_ffi_fn_method_moqannouncedbroadcast_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqannouncement-broadcast "uniffi_moq_ffi_fn_method_moqannouncement_broadcast" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqannouncement-path "uniffi_moq_ffi_fn_method_moqannouncement_path" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqaudioconsumer-cancel "uniffi_moq_ffi_fn_method_moqaudioconsumer_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqaudioconsumer-next "uniffi_moq_ffi_fn_method_moqaudioconsumer_next" [:uint64] :uint64)
(ffi/defcfn method-moqaudioproducer-finish "uniffi_moq_ffi_fn_method_moqaudioproducer_finish" [:uint64 :pointer] :void)
(ffi/defcfn method-moqaudioproducer-name "uniffi_moq_ffi_fn_method_moqaudioproducer_name" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqaudioproducer-reset-epoch "uniffi_moq_ffi_fn_method_moqaudioproducer_reset_epoch" [:uint64 :pointer] :void)
(ffi/defcfn method-moqaudioproducer-unused "uniffi_moq_ffi_fn_method_moqaudioproducer_unused" [:uint64] :uint64)
(ffi/defcfn method-moqaudioproducer-used "uniffi_moq_ffi_fn_method_moqaudioproducer_used" [:uint64] :uint64)
(ffi/defcfn method-moqaudioproducer-write "uniffi_moq_ffi_fn_method_moqaudioproducer_write" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqbroadcastconsumer-fetch-group "uniffi_moq_ffi_fn_method_moqbroadcastconsumer_fetch_group" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]]] :uint64)
(ffi/defcfn method-moqbroadcastconsumer-fetch-media-group "uniffi_moq_ffi_fn_method_moqbroadcastconsumer_fetch_media_group" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]]] :uint64)
(ffi/defcfn method-moqbroadcastconsumer-route "uniffi_moq_ffi_fn_method_moqbroadcastconsumer_route" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqbroadcastconsumer-route-updates "uniffi_moq_ffi_fn_method_moqbroadcastconsumer_route_updates" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqbroadcastconsumer-subscribe-audio "uniffi_moq_ffi_fn_method_moqbroadcastconsumer_subscribe_audio" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]]] :uint64)
(ffi/defcfn method-moqbroadcastconsumer-subscribe-catalog "uniffi_moq_ffi_fn_method_moqbroadcastconsumer_subscribe_catalog" [:uint64] :uint64)
(ffi/defcfn method-moqbroadcastconsumer-subscribe-json-snapshot "uniffi_moq_ffi_fn_method_moqbroadcastconsumer_subscribe_json_snapshot" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]]] :uint64)
(ffi/defcfn method-moqbroadcastconsumer-subscribe-json-stream "uniffi_moq_ffi_fn_method_moqbroadcastconsumer_subscribe_json_stream" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]]] :uint64)
(ffi/defcfn method-moqbroadcastconsumer-subscribe-media "uniffi_moq_ffi_fn_method_moqbroadcastconsumer_subscribe_media" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]]] :uint64)
(ffi/defcfn method-moqbroadcastconsumer-subscribe-track "uniffi_moq_ffi_fn_method_moqbroadcastconsumer_subscribe_track" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]]] :uint64)
(ffi/defcfn method-moqbroadcastdynamic-cancel "uniffi_moq_ffi_fn_method_moqbroadcastdynamic_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqbroadcastdynamic-requested-track "uniffi_moq_ffi_fn_method_moqbroadcastdynamic_requested_track" [:uint64] :uint64)
(ffi/defcfn method-moqbroadcastproducer-consume "uniffi_moq_ffi_fn_method_moqbroadcastproducer_consume" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqbroadcastproducer-dynamic "uniffi_moq_ffi_fn_method_moqbroadcastproducer_dynamic" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqbroadcastproducer-finish "uniffi_moq_ffi_fn_method_moqbroadcastproducer_finish" [:uint64 :pointer] :void)
(ffi/defcfn method-moqbroadcastproducer-publish-audio "uniffi_moq_ffi_fn_method_moqbroadcastproducer_publish_audio" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqbroadcastproducer-publish-json-snapshot "uniffi_moq_ffi_fn_method_moqbroadcastproducer_publish_json_snapshot" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqbroadcastproducer-publish-json-stream "uniffi_moq_ffi_fn_method_moqbroadcastproducer_publish_json_stream" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqbroadcastproducer-publish-media "uniffi_moq_ffi_fn_method_moqbroadcastproducer_publish_media" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqbroadcastproducer-publish-media-on-track "uniffi_moq_ffi_fn_method_moqbroadcastproducer_publish_media_on_track" [:uint64 :uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqbroadcastproducer-publish-media-stream "uniffi_moq_ffi_fn_method_moqbroadcastproducer_publish_media_stream" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqbroadcastproducer-publish-track "uniffi_moq_ffi_fn_method_moqbroadcastproducer_publish_track" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqbroadcastproducer-publish-video "uniffi_moq_ffi_fn_method_moqbroadcastproducer_publish_video" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqbroadcastproducer-remove-catalog-section "uniffi_moq_ffi_fn_method_moqbroadcastproducer_remove_catalog_section" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqbroadcastproducer-set-announce "uniffi_moq_ffi_fn_method_moqbroadcastproducer_set_announce" [:uint64 :int8 :pointer] :void)
(ffi/defcfn method-moqbroadcastproducer-set-catalog-section "uniffi_moq_ffi_fn_method_moqbroadcastproducer_set_catalog_section" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqbroadcastproducer-set-route "uniffi_moq_ffi_fn_method_moqbroadcastproducer_set_route" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqbroadcastproducer-set-video-properties "uniffi_moq_ffi_fn_method_moqbroadcastproducer_set_video_properties" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqbroadcastrequest-abort "uniffi_moq_ffi_fn_method_moqbroadcastrequest_abort" [:uint64 :uint16 :pointer] :void)
(ffi/defcfn method-moqbroadcastrequest-accept "uniffi_moq_ffi_fn_method_moqbroadcastrequest_accept" [:uint64 :uint64 :pointer] :void)
(ffi/defcfn method-moqbroadcastrequest-path "uniffi_moq_ffi_fn_method_moqbroadcastrequest_path" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqcatalogconsumer-cancel "uniffi_moq_ffi_fn_method_moqcatalogconsumer_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqcatalogconsumer-next "uniffi_moq_ffi_fn_method_moqcatalogconsumer_next" [:uint64] :uint64)
(ffi/defcfn method-moqclient-cancel "uniffi_moq_ffi_fn_method_moqclient_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqclient-connect "uniffi_moq_ffi_fn_method_moqclient_connect" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]]] :uint64)
(ffi/defcfn method-moqclient-set-bind "uniffi_moq_ffi_fn_method_moqclient_set_bind" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqclient-set-consume "uniffi_moq_ffi_fn_method_moqclient_set_consume" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqclient-set-publish "uniffi_moq_ffi_fn_method_moqclient_set_publish" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqclient-set-tls-cert "uniffi_moq_ffi_fn_method_moqclient_set_tls_cert" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqclient-set-tls-disable-verify "uniffi_moq_ffi_fn_method_moqclient_set_tls_disable_verify" [:uint64 :int8 :pointer] :void)
(ffi/defcfn method-moqclient-set-tls-fingerprints "uniffi_moq_ffi_fn_method_moqclient_set_tls_fingerprints" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqclient-set-tls-key "uniffi_moq_ffi_fn_method_moqclient_set_tls_key" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqclient-set-tls-roots "uniffi_moq_ffi_fn_method_moqclient_set_tls_roots" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqclient-set-tls-system-roots "uniffi_moq_ffi_fn_method_moqclient_set_tls_system_roots" [:uint64 :int8 :pointer] :void)
(ffi/defcfn method-moqgroupconsumer-cancel "uniffi_moq_ffi_fn_method_moqgroupconsumer_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqgroupconsumer-read-frame "uniffi_moq_ffi_fn_method_moqgroupconsumer_read_frame" [:uint64] :uint64)
(ffi/defcfn method-moqgroupconsumer-sequence "uniffi_moq_ffi_fn_method_moqgroupconsumer_sequence" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqgroupproducer-abort "uniffi_moq_ffi_fn_method_moqgroupproducer_abort" [:uint64 :uint16 :pointer] :void)
(ffi/defcfn method-moqgroupproducer-consume "uniffi_moq_ffi_fn_method_moqgroupproducer_consume" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqgroupproducer-finish "uniffi_moq_ffi_fn_method_moqgroupproducer_finish" [:uint64 :pointer] :void)
(ffi/defcfn method-moqgroupproducer-sequence "uniffi_moq_ffi_fn_method_moqgroupproducer_sequence" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqgroupproducer-write-frame "uniffi_moq_ffi_fn_method_moqgroupproducer_write_frame" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqgrouprequest-abort "uniffi_moq_ffi_fn_method_moqgrouprequest_abort" [:uint64 :uint16 :pointer] :void)
(ffi/defcfn method-moqgrouprequest-accept "uniffi_moq_ffi_fn_method_moqgrouprequest_accept" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqgrouprequest-priority "uniffi_moq_ffi_fn_method_moqgrouprequest_priority" [:uint64 :pointer] :uint8)
(ffi/defcfn method-moqgrouprequest-sequence "uniffi_moq_ffi_fn_method_moqgrouprequest_sequence" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqjsonsnapshotconsumer-cancel "uniffi_moq_ffi_fn_method_moqjsonsnapshotconsumer_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqjsonsnapshotconsumer-next "uniffi_moq_ffi_fn_method_moqjsonsnapshotconsumer_next" [:uint64] :uint64)
(ffi/defcfn method-moqjsonsnapshotproducer-finish "uniffi_moq_ffi_fn_method_moqjsonsnapshotproducer_finish" [:uint64 :pointer] :void)
(ffi/defcfn method-moqjsonsnapshotproducer-update "uniffi_moq_ffi_fn_method_moqjsonsnapshotproducer_update" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqjsonstreamconsumer-cancel "uniffi_moq_ffi_fn_method_moqjsonstreamconsumer_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqjsonstreamconsumer-next "uniffi_moq_ffi_fn_method_moqjsonstreamconsumer_next" [:uint64] :uint64)
(ffi/defcfn method-moqjsonstreamproducer-append "uniffi_moq_ffi_fn_method_moqjsonstreamproducer_append" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqjsonstreamproducer-finish "uniffi_moq_ffi_fn_method_moqjsonstreamproducer_finish" [:uint64 :pointer] :void)
(ffi/defcfn method-moqmediaconsumer-cancel "uniffi_moq_ffi_fn_method_moqmediaconsumer_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqmediaconsumer-next "uniffi_moq_ffi_fn_method_moqmediaconsumer_next" [:uint64] :uint64)
(ffi/defcfn method-moqmediagroupconsumer-cancel "uniffi_moq_ffi_fn_method_moqmediagroupconsumer_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqmediagroupconsumer-next "uniffi_moq_ffi_fn_method_moqmediagroupconsumer_next" [:uint64] :uint64)
(ffi/defcfn method-moqmediagroupconsumer-sequence "uniffi_moq_ffi_fn_method_moqmediagroupconsumer_sequence" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqmediaproducer-finish "uniffi_moq_ffi_fn_method_moqmediaproducer_finish" [:uint64 :pointer] :void)
(ffi/defcfn method-moqmediaproducer-name "uniffi_moq_ffi_fn_method_moqmediaproducer_name" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqmediaproducer-unused "uniffi_moq_ffi_fn_method_moqmediaproducer_unused" [:uint64] :uint64)
(ffi/defcfn method-moqmediaproducer-used "uniffi_moq_ffi_fn_method_moqmediaproducer_used" [:uint64] :uint64)
(ffi/defcfn method-moqmediaproducer-write-frame "uniffi_moq_ffi_fn_method_moqmediaproducer_write_frame" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqmediastreamproducer-finish "uniffi_moq_ffi_fn_method_moqmediastreamproducer_finish" [:uint64 :pointer] :void)
(ffi/defcfn method-moqmediastreamproducer-write "uniffi_moq_ffi_fn_method_moqmediastreamproducer_write" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqoriginconsumer-announced "uniffi_moq_ffi_fn_method_moqoriginconsumer_announced" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqoriginconsumer-announced-broadcast "uniffi_moq_ffi_fn_method_moqoriginconsumer_announced_broadcast" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqoriginconsumer-request-broadcast "uniffi_moq_ffi_fn_method_moqoriginconsumer_request_broadcast" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]]] :uint64)
(ffi/defcfn method-moqorigindynamic-cancel "uniffi_moq_ffi_fn_method_moqorigindynamic_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqorigindynamic-requested-broadcast "uniffi_moq_ffi_fn_method_moqorigindynamic_requested_broadcast" [:uint64] :uint64)
(ffi/defcfn method-moqoriginproducer-consume "uniffi_moq_ffi_fn_method_moqoriginproducer_consume" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqoriginproducer-create-broadcast "uniffi_moq_ffi_fn_method_moqoriginproducer_create_broadcast" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqoriginproducer-dynamic "uniffi_moq_ffi_fn_method_moqoriginproducer_dynamic" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqrequest-accept "uniffi_moq_ffi_fn_method_moqrequest_accept" [:uint64] :uint64)
(ffi/defcfn method-moqrequest-cancel "uniffi_moq_ffi_fn_method_moqrequest_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqrequest-path "uniffi_moq_ffi_fn_method_moqrequest_path" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqrequest-query "uniffi_moq_ffi_fn_method_moqrequest_query" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqrequest-reject "uniffi_moq_ffi_fn_method_moqrequest_reject" [:uint64 :uint16] :uint64)
(ffi/defcfn method-moqrequest-set-consume "uniffi_moq_ffi_fn_method_moqrequest_set_consume" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqrequest-set-publish "uniffi_moq_ffi_fn_method_moqrequest_set_publish" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqrequest-transport "uniffi_moq_ffi_fn_method_moqrequest_transport" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqrequest-url "uniffi_moq_ffi_fn_method_moqrequest_url" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqroutewatch-cancel "uniffi_moq_ffi_fn_method_moqroutewatch_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqroutewatch-next "uniffi_moq_ffi_fn_method_moqroutewatch_next" [:uint64] :uint64)
(ffi/defcfn method-moqserver-accept "uniffi_moq_ffi_fn_method_moqserver_accept" [:uint64] :uint64)
(ffi/defcfn method-moqserver-cancel "uniffi_moq_ffi_fn_method_moqserver_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqserver-cert-fingerprints "uniffi_moq_ffi_fn_method_moqserver_cert_fingerprints" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqserver-listen "uniffi_moq_ffi_fn_method_moqserver_listen" [:uint64] :uint64)
(ffi/defcfn method-moqserver-set-bind "uniffi_moq_ffi_fn_method_moqserver_set_bind" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqserver-set-consume "uniffi_moq_ffi_fn_method_moqserver_set_consume" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqserver-set-publish "uniffi_moq_ffi_fn_method_moqserver_set_publish" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqserver-set-tls-cert "uniffi_moq_ffi_fn_method_moqserver_set_tls_cert" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqserver-set-tls-generate "uniffi_moq_ffi_fn_method_moqserver_set_tls_generate" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqserver-set-tls-key "uniffi_moq_ffi_fn_method_moqserver_set_tls_key" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqsession-cancel "uniffi_moq_ffi_fn_method_moqsession_cancel" [:uint64 :uint32 :pointer] :void)
(ffi/defcfn method-moqsession-closed "uniffi_moq_ffi_fn_method_moqsession_closed" [:uint64] :uint64)
(ffi/defcfn method-moqsession-consumer "uniffi_moq_ffi_fn_method_moqsession_consumer" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqsession-publisher "uniffi_moq_ffi_fn_method_moqsession_publisher" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqsession-shutdown "uniffi_moq_ffi_fn_method_moqsession_shutdown" [:uint64 :pointer] :void)
(ffi/defcfn method-moqsession-stats "uniffi_moq_ffi_fn_method_moqsession_stats" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqtrackconsumer-cancel "uniffi_moq_ffi_fn_method_moqtrackconsumer_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqtrackconsumer-info "uniffi_moq_ffi_fn_method_moqtrackconsumer_info" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqtrackconsumer-next-group "uniffi_moq_ffi_fn_method_moqtrackconsumer_next_group" [:uint64] :uint64)
(ffi/defcfn method-moqtrackconsumer-read-frame "uniffi_moq_ffi_fn_method_moqtrackconsumer_read_frame" [:uint64] :uint64)
(ffi/defcfn method-moqtrackconsumer-recv-datagram "uniffi_moq_ffi_fn_method_moqtrackconsumer_recv_datagram" [:uint64] :uint64)
(ffi/defcfn method-moqtrackconsumer-recv-group "uniffi_moq_ffi_fn_method_moqtrackconsumer_recv_group" [:uint64] :uint64)
(ffi/defcfn method-moqtrackconsumer-update "uniffi_moq_ffi_fn_method_moqtrackconsumer_update" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqtrackdynamic-cancel "uniffi_moq_ffi_fn_method_moqtrackdynamic_cancel" [:uint64 :pointer] :void)
(ffi/defcfn method-moqtrackdynamic-requested-group "uniffi_moq_ffi_fn_method_moqtrackdynamic_requested_group" [:uint64] :uint64)
(ffi/defcfn method-moqtrackproducer-abort "uniffi_moq_ffi_fn_method_moqtrackproducer_abort" [:uint64 :uint16 :pointer] :void)
(ffi/defcfn method-moqtrackproducer-append-datagram "uniffi_moq_ffi_fn_method_moqtrackproducer_append_datagram" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqtrackproducer-append-group "uniffi_moq_ffi_fn_method_moqtrackproducer_append_group" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqtrackproducer-consume "uniffi_moq_ffi_fn_method_moqtrackproducer_consume" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqtrackproducer-create-group "uniffi_moq_ffi_fn_method_moqtrackproducer_create_group" [:uint64 :uint64 :pointer] :uint64)
(ffi/defcfn method-moqtrackproducer-dynamic "uniffi_moq_ffi_fn_method_moqtrackproducer_dynamic" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqtrackproducer-finish "uniffi_moq_ffi_fn_method_moqtrackproducer_finish" [:uint64 :pointer] :void)
(ffi/defcfn method-moqtrackproducer-finish-at "uniffi_moq_ffi_fn_method_moqtrackproducer_finish_at" [:uint64 :uint64 :pointer] :void)
(ffi/defcfn method-moqtrackproducer-name "uniffi_moq_ffi_fn_method_moqtrackproducer_name" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqtrackproducer-unused "uniffi_moq_ffi_fn_method_moqtrackproducer_unused" [:uint64] :uint64)
(ffi/defcfn method-moqtrackproducer-used "uniffi_moq_ffi_fn_method_moqtrackproducer_used" [:uint64] :uint64)
(ffi/defcfn method-moqtrackproducer-write-frame "uniffi_moq_ffi_fn_method_moqtrackproducer_write_frame" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
(ffi/defcfn method-moqtrackrequest-abort "uniffi_moq_ffi_fn_method_moqtrackrequest_abort" [:uint64 :uint16 :pointer] :void)
(ffi/defcfn method-moqtrackrequest-accept "uniffi_moq_ffi_fn_method_moqtrackrequest_accept" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :uint64)
(ffi/defcfn method-moqtrackrequest-dynamic "uniffi_moq_ffi_fn_method_moqtrackrequest_dynamic" [:uint64 :pointer] :uint64)
(ffi/defcfn method-moqtrackrequest-name "uniffi_moq_ffi_fn_method_moqtrackrequest_name" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqvideoproducer-cut "uniffi_moq_ffi_fn_method_moqvideoproducer_cut" [:uint64 :pointer] :void)
(ffi/defcfn method-moqvideoproducer-finish "uniffi_moq_ffi_fn_method_moqvideoproducer_finish" [:uint64 :pointer] :void)
(ffi/defcfn method-moqvideoproducer-name "uniffi_moq_ffi_fn_method_moqvideoproducer_name" [:uint64 :pointer] [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]])
(ffi/defcfn method-moqvideoproducer-set-bitrate "uniffi_moq_ffi_fn_method_moqvideoproducer_set_bitrate" [:uint64 :uint64 :pointer] :void)
(ffi/defcfn method-moqvideoproducer-unused "uniffi_moq_ffi_fn_method_moqvideoproducer_unused" [:uint64] :uint64)
(ffi/defcfn method-moqvideoproducer-used "uniffi_moq_ffi_fn_method_moqvideoproducer_used" [:uint64] :uint64)
(ffi/defcfn method-moqvideoproducer-write "uniffi_moq_ffi_fn_method_moqvideoproducer_write" [:uint64 [:by-value [:struct [[:capacity :uint64] [:len :uint64] [:data :pointer]]]] :pointer] :void)
