#!/usr/bin/env python3
"""Generate nim/src/frq/emoji.nim from common/frq/emoji.cljc.

The catalogue is 1,885 rows of data that Unicode generated in the first
place — retyping it by hand into a second language is how the two copies
start disagreeing. This reads the Clojure and emits the Nim, so the port is
a transcription a machine did and can redo.

    python3 tools/emoji2nim.py
"""
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
src = (root / "common/frq/emoji.cljc").read_text()
out = root / "nim/src/frq/emoji.nim"

def strings(block: str):
    """Every "..." in order, with Clojure's escapes undone."""
    return [s.encode().decode("unicode_escape") if "\\" in s else s
            for s in re.findall(r'"((?:[^"\\]|\\.)*)"', block)]

def section(name: str) -> str:
    # To the next top-level `(def ` or to EOF — `catalog` is last in the file
    # and has no blank line after it.
    m = re.search(r'\(def ' + name + r'\b(.*?)(?=\n\(def |\Z)', src, re.S)
    if not m:
        sys.exit(f"emoji2nim: no `(def {name} ...)` in emoji.cljc")
    body = m.group(1)
    # Drop the docstring, which is the first string and full of prose.
    return body[body.index("["):] if "[" in body else body

popular = strings(section("popular"))
groups = strings(section("groups"))
rows = [strings(r) for r in re.findall(r'\["(?:[^"\\]|\\.)*"\s+"(?:[^"\\]|\\.)*"\s+"(?:[^"\\]|\\.)*"\]',
                                       section("catalog"))]

def nimstr(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

lines = [
    "## Every emoji this client can draw, with the name to search it by.",
    "##",
    "## GENERATED by tools/emoji2nim.py from common/frq/emoji.cljc. Do not edit:",
    "## the catalogue is Unicode's own `emoji-test.txt` (15.1), filtered to what",
    "## the Twemoji pack has a picture for, and a second hand-maintained copy is",
    "## how the two languages start disagreeing about what can be drawn.",
    "##",
    "## Skin-tone variants are left out — they multiply the list by five and say",
    "## nothing a reaction needs to say. `glyphs` strips a tone before looking a",
    "## glyph up here, and keeps it for the drawing.",
    "",
    "type",
    "  Emoji* = object",
    "    glyph*, name*, group*: string",
    "",
    "const",
    "  popular* = [",
    "    " + ", ".join(nimstr(p) for p in popular),
    "  ]",
    "    ## What a reaction usually is. The picker opens on these, because the",
    "    ## whole point of reacting is that it costs less than typing.",
    "",
    "  groups* = [",
    "    " + ",\n    ".join(nimstr(g) for g in groups),
    "  ]",
    "",
    f"  catalog*: array[{len(rows)}, Emoji] = [",
]
for glyph, name, group in rows:
    lines.append(f"    Emoji(glyph: {nimstr(glyph)}, name: {nimstr(name)}, "
                 f"group: {nimstr(group)}),")
lines += ["  ]", ""]

out.write_text("\n".join(lines))
print(f"wrote {out.relative_to(root)}: {len(rows)} emoji, "
      f"{len(popular)} popular, {len(groups)} groups")
